### PR TITLE
Fix timed out tests not showing tracebacks, use SIGINT

### PR DESCRIPTION
**Pull request by Cynerva**
If we send SIGINT when a timeout occurs, that will raise a KeyboardInterrupt exception in the Python code and show us a traceback. That should help us see exactly where tests are getting stuck.

### CODE REVIEW

**Comment by Cynerva** [comment]
I did `git grep 'timeout.*pytest'` and just added `-s INT` to every instance I saw.

**Review by johnsca — CHANGES_REQUESTED** [review]
I tested the `timeout -s INT` and it seems that pytest will hide the traceback specifically for `KeyboardInterrupt`:

```
/home/johnsca/juju/envs/dev/charms/kubernetes-master/tests/unit/test_kubernetes_master.py:66: KeyboardInterrupt
(to show a full traceback on KeyboardInterrupt use --full-trace)
```

I think we need to add the `--full-trace`.  Adding that gave the trace info in my test, but it's worth noting that `--full-trace` seems to override `--tb=native` but I think actually having the debug info is worth the more verbose traceback style.

**Comment by Cynerva** [comment]
Good catch, thanks. I've added the `--full-trace` arg to pytest now too.

**Review by johnsca — APPROVED** [review]
LGTM

**Pull request merged**
