### PR TITLE
Change ClusterIP port LP#1983990

### PR DESCRIPTION
**Pull request by mateoflorido**
## Changes
- Changed ClusterIP port to avoid port collision.
## Tests
- [AWS](https://pastebin.ubuntu.com/p/yBN52WwpwT/)
- [vSphere](https://pastebin.ubuntu.com/p/zFFcGb28K4/)

### CODE REVIEW

**Comment by Cynerva** [comment]
What is port 80 on the service colliding with?

**Review by addyess — APPROVED** [review]
fine by me

**Comment by Cynerva** [comment]
Can you help me understand the problem here? How did you determine that port 80 is the problem?

**Comment by mateoflorido** [comment]
Sometimes ClusterIP tests failed on AWS. Nevertheless, it is an isolated issue and I have only seen it once on AWS. However, running again the tests with the `80` port it looks like it's working again. You are right, it is not the right fix. Closing.

**Pull request closed without merging**
