### PR TITLE
Infra sync/charmcraft

### PR DESCRIPTION
**Pull request by addyess**
adding credentials for accessing charmhub to ci-master

### CODE REVIEW

**Comment by addyess** [comment]
microk8s folks, can you confirm this doesn't collide or impede your job [`build-microk8s-charm`](github.com/charmed-kubernetes/jenkins/blob/master/jobs/build-microk8s-charm.yaml#L13-L16)

these new creds were added for `build-charms` and `promote` jobs but we realized after the fact it could interfere with your build.   Our new creds are that of `cdk_bot`

**Review by kwmonroe — APPROVED** [review]
LGTM pending uk8s approval.

**Review by neoaggelos — APPROVED** [review]
+1, it does not affect MicroK8s jobs (for reference, the MicroK8s job definitions do not use the `ci-creds` wrapper, see https://github.com/charmed-kubernetes/jenkins/blob/master/jobs/build-microk8s-charm.yaml#L9-L16 and https://github.com/charmed-kubernetes/jenkins/blob/master/jobs/build-microk8s-charm.yaml#L58-L68)

**Comment by addyess** [comment]
thanks @neoaggelos,  merging

**Pull request merged**
