### PR TITLE
Adding Docker test back in and placeholding Containerd

### PR DESCRIPTION
**Pull request by joedborg**
Is there a way we can call these with different bundles?

### CODE REVIEW

**Comment by battlemidget** [comment]
Yea we can, do you have the bundles handy?

**Comment by joedborg** [comment]
Sweet!

Containerd
```yaml
description: A highly-available, production-grade Kubernetes cluster.
series: bionic
services:
  containerd:
    charm: cs:~containers/containerd-2
    resources: {}
  easyrsa:
    annotations:
      gui-x: '450'
      gui-y: '550'
    charm: cs:~containers/easyrsa-254
    constraints: root-disk=8G
    num_units: 1
    resources:
      easyrsa: 5
  etcd:
    annotations:
      gui-x: '800'
      gui-y: '550'
    charm: cs:~containers/etcd-434
    constraints: root-disk=8G
    num_units: 3
    options:
      channel: 3.2/stable
    resources:
      core: 0
      etcd: 3
      snapshot: 0
  flannel:
    annotations:
      gui-x: '450'
      gui-y: '750'
    charm: cs:~containers/flannel-425
    resources:
      flannel-amd64: 323
      flannel-arm64: 319
      flannel-s390x: 306
  kubeapi-load-balancer:
    annotations:
      gui-x: '450'
      gui-y: '250'
    charm: cs:~containers/kubeapi-load-balancer-649
    constraints: root-disk=8G
    expose: true
    num_units: 1
    resources: {}
  kubernetes-master:
    annotations:
      gui-x: '800'
      gui-y: '850'
    charm: cs:~containers/kubernetes-master-700
    constraints: cores=2 mem=4G root-disk=16G
    num_units: 2
    options:
      channel: 1.15/stable
    resources:
      cdk-addons: 0
      core: 0
      kube-apiserver: 0
      kube-controller-manager: 0
      kube-proxy: 0
      kube-scheduler: 0
      kubectl: 0
  kubernetes-worker:
    annotations:
      gui-x: '100'
      gui-y: '850'
    charm: cs:~containers/kubernetes-worker-552
    constraints: cores=4 mem=4G root-disk=16G
    expose: true
    num_units: 3
    options:
      channel: 1.15/stable
    resources:
      cni-amd64: 322
      cni-arm64: 313
      cni-s390x: 325
      core: 0
      kube-proxy: 0
      kubectl: 0
      kubelet: 0
relations:
- - kubernetes-master:kube-api-endpoint
  - kubeapi-load-balancer:apiserver
- - kubernetes-master:loadbalancer
  - kubeapi-load-balancer:loadbalancer
- - kubernetes-master:kube-control
  - kubernetes-worker:kube-control
- - kubernetes-master:certificates
  - easyrsa:client
- - etcd:certificates
  - easyrsa:client
- - kubernetes-master:etcd
  - etcd:db
- - kubernetes-worker:certificates
  - easyrsa:client
- - kubernetes-worker:kube-api-endpoint
  - kubeapi-load-balancer:website
- - kubeapi-load-balancer:certificates
  - easyrsa:client
- - flannel:etcd
  - etcd:db
- - flannel:cni
  - kubernetes-master:cni
- - flannel:cni
  - kubernetes-worker:cni
- - containerd:containerd
  - kubernetes-worker:container-runtime
- - containerd:containerd
  - kubernetes-master:container-runtime
```

Docker
```yaml
description: A highly-available, production-grade Kubernetes cluster.
series: bionic
services:
  docker:
    charm: cs:~containers/docker-1
    resources: {}
  easyrsa:
    annotations:
      gui-x: '450'
      gui-y: '550'
    charm: cs:~containers/easyrsa-254
    constraints: root-disk=8G
    num_units: 1
    resources:
      easyrsa: 5
  etcd:
    annotations:
      gui-x: '800'
      gui-y: '550'
    charm: cs:~containers/etcd-434
    constraints: root-disk=8G
    num_units: 3
    options:
      channel: 3.2/stable
    resources:
      core: 0
      etcd: 3
      snapshot: 0
  flannel:
    annotations:
      gui-x: '450'
      gui-y: '750'
    charm: cs:~containers/flannel-425
    resources:
      flannel-amd64: 323
      flannel-arm64: 319
      flannel-s390x: 306
  kubeapi-load-balancer:
    annotations:
      gui-x: '450'
      gui-y: '250'
    charm: cs:~containers/kubeapi-load-balancer-649
    constraints: root-disk=8G
    expose: true
    num_units: 1
    resources: {}
  kubernetes-master:
    annotations:
      gui-x: '800'
      gui-y: '850'
    charm: cs:~containers/kubernetes-master-700
    constraints: cores=2 mem=4G root-disk=16G
    num_units: 2
    options:
      channel: 1.15/stable
    resources:
      cdk-addons: 0
      core: 0
      kube-apiserver: 0
      kube-controller-manager: 0
      kube-proxy: 0
      kube-scheduler: 0
      kubectl: 0
  kubernetes-worker:
    annotations:
      gui-x: '100'
      gui-y: '850'
    charm: cs:~containers/kubernetes-worker-552
    constraints: cores=4 mem=4G root-disk=16G
    expose: true
    num_units: 3
    options:
      channel: 1.15/stable
    resources:
      cni-amd64: 322
      cni-arm64: 313
      cni-s390x: 325
      core: 0
      kube-proxy: 0
      kubectl: 0
      kubelet: 0
relations:
- - kubernetes-master:kube-api-endpoint
  - kubeapi-load-balancer:apiserver
- - kubernetes-master:loadbalancer
  - kubeapi-load-balancer:loadbalancer
- - kubernetes-master:kube-control
  - kubernetes-worker:kube-control
- - kubernetes-master:certificates
  - easyrsa:client
- - etcd:certificates
  - easyrsa:client
- - kubernetes-master:etcd
  - etcd:db
- - kubernetes-worker:certificates
  - easyrsa:client
- - kubernetes-worker:kube-api-endpoint
  - kubeapi-load-balancer:website
- - kubeapi-load-balancer:certificates
  - easyrsa:client
- - flannel:etcd
  - etcd:db
- - flannel:cni
  - kubernetes-master:cni
- - flannel:cni
  - kubernetes-worker:cni
- - docker:docker
  - kubernetes-worker:container-runtime
- - docker:docker
  - kubernetes-master:container-runtime
```

**Comment by joedborg** [comment]
[Docker specific tests](https://trello.com/c/0qmJc5tK/1307-docker-specific-tests)

**Comment by battlemidget** [comment]
@joedborg I was going to include your bundles in the PR but I think we should try to get this generated using the bundle script from https://github.com/charmed-kubernetes/bundle? That way we can always build the bundles with the correct revisions from the charm channels we're deploying/testing. What do you think?

**Comment by battlemidget** [comment]
merging what we have, hopefully we can go the route of bundle generation

**Pull request merged**
